/***************************************************
 * Created by nanyuantingfeng on 2019/11/26 12:22. *
 ***************************************************/
import { PureCollection, PureModel } from 'datx'
import { IRawModel } from 'datx-utils'

import { fetchModelRefs, removeModel, saveModel } from './helpers/model'
import { ISkeletonModel, IRequestOptions, ISkeletonModelConstructor } from '../interfaces'

export function decorateModel(BaseClass: typeof PureModel) {
  class SkeletonModel extends BaseClass implements ISkeletonModel {
    public static useAutogeneratedIds: boolean = (BaseClass as any)['useAutogeneratedIds'] || false
    public static endpoint: string | (() => string)

    constructor(rawData: IRawModel, collection?: PureCollection) {
      super(rawData, collection)
    }

    public save(options?: IRequestOptions): Promise<ISkeletonModel> {
      return saveModel(this, options)
    }

    public remove(options?: IRequestOptions): Promise<void> {
      return removeModel(this, options)
    }

    fetchRefs(): Promise<PureModel[]> {
      return fetchModelRefs(this)
    }
  }

  return (SkeletonModel as unknown) as ISkeletonModelConstructor<PureModel & ISkeletonModel>
}
