/***************************************************
 * Created by nanyuantingfeng on 2019/11/26 12:22. *
 ***************************************************/
import { IModelConstructor, PureModel } from 'datx'
import { IRequestOptions } from './IRequestOptions'

export interface ISkeletonModel extends PureModel {
  save(options?: IRequestOptions): Promise<ISkeletonModel>
  remove(options?: IRequestOptions): Promise<void>
  fetchRefs(): Promise<PureModel[]>
}

export interface ISkeletonModelConstructor<T> extends IModelConstructor<T> {
  useAutogeneratedIds: boolean
  endpoint: string | (() => string)
}
